### ISSUE TITLE
Incompatibilities

### ISSUE THREAD

**Issue by GwenBlanketKnight** [tophatcats-mods/spooky-biomes#11]
https://www.curseforge.com/minecraft/mc-mods/mist-biomes with this installed your biomes lose their mist
https://www.curseforge.com/minecraft/mc-mods/welcome-to-the-jungle same happens here.

both of those add their own misty biomes.

**Comment by ProxyNeko** [comment]
Thanks for reminding me, will have a look as soon as I can to try and see what's causing it :)

**Comment by ProxyNeko** [comment]
I've spoken with the dev of Mist Biomes and he's said he will update the code in Mist Biomes to match his other mod (Fog World) that should stop Spooky Biomes and Fog World canceling each other out, I can't do much for Welcome to the Jungle right now but I'll give it a shot with the help of the Mist Biomes dev again :)

**Comment by GwenBlanketKnight** [comment]
thanks

**Comment by GwenBlanketKnight** [comment]
any luck?

**Comment by ProxyNeko** [comment]
So far the other mods have not released updated code so when I can I'll do so on my end, been hectic recently so there has been delay

**Comment by GwenBlanketKnight** [comment]
no rush. i mod games as well. i understand that real life gets in the way. take all the time you need.

**Comment by GwenBlanketKnight** [comment]
been trying to figure out a solution on my own but no luck.

**Comment by ProxyNeko** [comment]
Being worked on today once I sort out the port issue I am having.

**Comment by KiriCattus** [comment]
After a long break due to family/personal mental  matters and what I assume is long past the period of you using the mod also due tot hat I'll close this issue as it's LONG evaded me how I can actually fix this without just ripping the code from the other mods (that I have permission from the author to do) and still keep it compatible with other mods. Post 1.12 will not have these same issues hopefully with Vanilla handling mist and such for us now. So sorry for the long wait and inability to fix this issue though :s
