### ISSUE TITLE
Vein Miner issues

### ISSUE THREAD

**Issue by SkyanUltra** [tophatcats-mods/spooky-biomes#8]
cool to see the mod got updated tonight! thanks for that.

with veinminer, ghostly tree logs that are sideways are considered a different block from the upwards logs and thus do not get veinmined. would appreciate it if this was fixed!

also, just a suggestion but some of the plank types should get changed again. ghostly planks look too much like birch planks so maybe base their colors a little bit off of the previous version. same with sorbus, but im not sure what you could do with them.

(one last question, is it normal for bloodied grass/dirt to be instantly breakable??)

going to bed now, its 2:30 am where i live lol

**Comment by ProxyNeko** [comment]
Bloodied grass being instantly breakable was an oversight on my part I can likely push out a patch for that later when I do the animation work if not on it’s own if I don’t have time.

Big ghostly trees with the logs sideways are based of vanilla big oak trees so if you could find some of those to test against with veinminer and report back that would be a great help (super busy irl at the moment and time is very sparse but dw if you can’t)

Textures I thought looked fine and so did the artist but I’ll at least look and see, no promises on changes there though since that is up to the artist if he has time and thinks the same.

Side notes:
- Curse forge page will be updated with newer info when I can get to it.
- Bloodwood trees are generating like small vanilla oaks for now with dirt under them this is going to be changed.
- Seeping logs are meant to be animated so that will be fixed as soon as.

**Comment by ProxyNeko** [comment]
@UltraGamesYT where you able to replicate the issue with vanilla big oak trees?

**Comment by ProxyNeko** [comment]
Closing as user has not replied.

**Comment by SkyanUltra** [comment]
whoops, sorry

veinminer works fine with vanilla logs, but spooky biomes doesn't have proper compatibility.

**Comment by ProxyNeko** [comment]
Actually come to think of it don't you have to add stuff to the config for vein miner to work? Coz I'm pretty sure you do, will check in a bit.

**Comment by SkyanUltra** [comment]
only sometimes. even so you should be able to add veinminer support without too much issues, i don't think its too hard to integrate into your mod considering its just a few blocks that need it.

**Comment by KiriCattus** [comment]
After totally forgetting and a long break due to personal/family reasons I came back and remembered I had to test this, turns out my mod WAS compatible with vein miner you just had to hold down the key to make it work..... Closing this as invalid due to that fact.
